Repository minhadona/Data_Engineer_Interview_Challenges, pull requests merged in 2022-10, with the labels that each got.

#10 playgroundxyz_selection_process_added
  2022_OCT_PLAYGROUND-XYZ_AU/bonus_etl_data_gen.txt
  2022_OCT_PLAYGROUND-XYZ_AU/challenge.md
  2022_OCT_PLAYGROUND-XYZ_AU/data.zip
  2022_OCT_PLAYGROUND-XYZ_AU/ddl.sql
  2022_OCT_PLAYGROUND-XYZ_AU/erd.png
Labels: hacktoberfest-2022, hacktoberfest

#11 prospa group challenge (2020)
  2020_JUL_PROSPA_AU/bonus_etl_data_gen.txt
  2020_JUL_PROSPA_AU/challenge.md
  2020_JUL_PROSPA_AU/data.zip
  2020_JUL_PROSPA_AU/ddl.sql
  2020_JUL_PROSPA_AU/erd.png
Labels: hacktoberfest-2022, hacktoberfest

#1 Boticário Group Practice Test
  2021-MAR-BOTICARIO/challenge.md
  2021-MAR-BOTICARIO/data/Base_2017_1.csv
  2021-MAR-BOTICARIO/data/Base_2018_2.csv
  2021-MAR-BOTICARIO/data/Base_2019_3.csv
Labels: hacktoberfest-2022, hacktoberfest

#15 privia health challenge w/ SQLTestQuestions
  2021_JUL_PRIVIA-HEALTH_US/SQLTestQuestions/PersonDatabase.sql
  2021_JUL_PRIVIA-HEALTH_US/SQLTestQuestions/TestQuestions.sql
  2021_JUL_PRIVIA-HEALTH_US/SQLTestQuestions/dbo.Contracts.txt
  2021_JUL_PRIVIA-HEALTH_US/challenge.md
Labels: good first issue, markdown-only, hacktoberfest-2022, for beginners, hacktoberfest

#16 folder missing to pythontestquestions
  2021_JUL_PRIVIA-HEALTH_US/PythonTestQuestions/Privia Family Medicine 113018.xlsx
  2021_JUL_PRIVIA-HEALTH_US/PythonTestQuestions/python_data_test_requirements.txt
Labels: help wanted, good first issue, markdown-only, hacktoberfest-2022, for beginners, hacktoberfest
